[package]
name = "image-file-name-fixer"
version = "0.0.0"
authors = ["Jeremy M. Reed <reeje76@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
